eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
   healthcheck:
      enabled: true   
  instance:
    prefer-ip-address: true
   #续约更新时间间隔
    lease-renewal-interval-in-seconds: 30
    #续约到期时间默认90秒
    lease-expiration-duration-in-seconds: 90
      
feign:
  hystrix:
    enabled: true


info:
  config: config-server 
